apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginx-argocd
spec:
  type: NodePort
  ports:
    - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
