
apiVersion: v1	apiVersion: v1
kind: Service	kind: Service
metadata:	metadata:
  namespace: default
  name: nginx-argocd-svc	  
    labels:	  labels:
    app: nginx-argocd
spec:	spec:
  type: NodePort
  ports:	  ports:
    - port: 80
  selector:	
    app: nginx-argocd	
---
apiVersion: apps/v1	
kind: Deployment	
metadata:	
  name: nginx-argocd-deployment	
  namespace: default
spec:	
  replicas: 1	
  selector:	
    matchLabels:	
      app: nginx-argocd	
  template:	
    metadata:	
      labels:	
        app: nginx-argocd	
    spec:	
      containers:	
        - name: nginx-container	
          image: nginx:latest	
          ports:	
            - containerPort: 80
