apiVersion: v1
kind: Service
metadata:
  name: nginx-argocd-svc
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: nginxinargocd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-argocd-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginxinargocd
  template:
    metadata:
      labels:
        app: nginxinargocd
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
