apiVersion: v1
kind: Service
metadata:	
  namespace: default
  name: nginx-argocd-svc
  labels:	
    app: nginx-argocd
spec:
  type: NodePort
  ports:
    - port: 80
  selector:	
    app: nginx-argocd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-argocd-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-argocd
  template:
    metadata:	
      labels:
        app: nginx-argocd
    spec:
      containers:
        - name: nginx-container
          image: quay.io/centos7/nginx-120-centos7
          ports:
            - containerPort: 80
